sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "node"
  - "iojs-v1.0.4" 
  - "iojs"

# Handle git submodules yourself
git:
   submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - npm test
  - npm run-script setup-database-test
  - npm run-script database-test
