sudo: false
language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "node"
  - "iojs-v1.0.4" 
  - "iojs"

before_script:
  - node web/server.js & 
  - sleep 5

script:
  - npm test
  - ./node_modules/casperjs/bin/casperjs test test/integration/*.js
